# Generated by Django 4.2 on 2023-04-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Rede')),
                ('ssid', models.CharField(max_length=32, verbose_name='SSID')),
                ('senha', models.CharField(max_length=16, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50, verbose_name='Nome da Rede')),
                ('num_serie', models.CharField(max_length=32, verbose_name='SSID')),
                ('rede_wifi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsl.rede')),
            ],
        ),
    ]
